apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /prometheus
    prometheus.io/port: 8081
    prometheus.io/scrape: true
  labels:
    application: helloworld
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
      application: helloworld
  type: NodePort
  sessionAffinity: None
